=== api-evangelist/snowflake/json-schema/account-account-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Account",
  "type": "object",
  "description": "Snowflake account object.",
  "properties": {
    "organization_name": {
      "type": "string",
      "description": "Name of the organization."
    },
    "region_group": {
      "type": "string",
      "description": "Region group where the account is located. Note - This column is only displayed for organizations that span multiple region groups."
    },
    "region": {
      "type": "string",
      "description": "Snowflake Region where the account is located. A Snowflake Region is a distinct location within a cloud platform region that is isolated from other Snowflake Regions. A Snowflake Region can be either multi-tenant or single-tenant (for a Virtual Private Snowflake account)."
    },
    "edition": {
      "type": "string",
      "description": "Snowflake Edition of the account."
    },
    "created_on": {
      "type": "string",
      "description": "Date and time the account was created."
    },
    "account_url": {
      "type": "string",
      "description": "Preferred Snowflake account URL that includes the values of organization_name and account_name."
    },
    "account_locator": {
      "type": "string",
      "description": "System-assigned identifier of the acccount."
    },
    "account_locator_url": {
      "type": "string",
      "description": "Legacy Snowflake account URL syntax that includes the region_name and account_locator."
    },
    "managed_accounts": {
      "type": "integer",
      "description": "Indicates how many managed accounts have been created by the account."
    },
    "consumption_billing_entity_name": {
      "type": "string",
      "description": "Name of the consumption billing entity."
    },
    "marketplace_consumer_billing_entity_name": {
      "type": "string",
      "description": "Name of the marketplace consumer billing entity."
    },
    "marketplace_provider_billing_entity_name": {
      "type": "string",
      "description": "Name of the marketplace provider billing entity."
    },
    "old_account_url": {
      "type": "string",
      "description": "If the original account URL was saved when the account was renamed, provides the original URL. If the original account URL was dropped, the value is NULL even if the account was renamed"
    },
    "comment": {
      "type": "string",
      "description": "Optional comment in which to store information related to the account."
    },
    "is_org_admin": {
      "type": "boolean",
      "description": "Indicates whether the ORGADMIN role is enabled in an account. If TRUE, the role is enabled."
    },
    "retention_time": {
      "type": "integer",
      "description": "Number of days that historical data is retained for Time Travel."
    },
    "dropped_on": {
      "type": "string",
      "description": "Date and time the account was dropped."
    },
    "scheduled_deletion_time": {
      "type": "string",
      "description": "Date and time when the account is scheduled to be permanently deleted. Accounts are deleted within one hour after the scheduled time."
    },
    "restored_on": {
      "type": "string",
      "description": "Date and time when the account was last restored."
    },
    "account_old_url_saved_on": {
      "type": "string",
      "description": "If the original account URL was saved when the account was renamed, provides the date and time when the original account URL was saved."
    },
    "account_old_url_last_used": {
      "type": "string",
      "description": "If the original account URL was saved when the account was renamed, indicates the last time the account was accessed using the original URL."
    },
    "organization_old_url": {
      "type": "string",
      "description": "If the account\u2019s organization was changed in a way that created a new account URL and the original account URL was saved, provides the original account URL. If the original account URL was dropped, the value is NULL even if the organization changed."
    },
    "organization_old_url_saved_on": {
      "type": "string",
      "description": "If the account\u2019s organization was changed in a way that created a new account URL and the original account URL was saved, provides the date and time when the original account URL was saved."
    },
    "organization_old_url_last_used": {
      "type": "string",
      "description": "If the account\u2019s organization was changed in a way that created a new account URL and the original account URL was saved, indicates the last time the account was accessed using the original account URL."
    },
    "organization_URL_expiration_on": {
      "type": "string",
      "description": "If the account\u2019s organization was changed in a way that created a new account URL and the original account URL was saved, provides the date and time when the original account URL will be dropped. Dropped URLs cannot be used to access the account."
    },
    "moved_on": {
      "type": "string",
      "description": "Date and time when the account was moved to a different organization."
    },
    "is_events_account": {
      "type": "boolean",
      "description": "Indicates whether an account is an events account. For more information, see Set up logging and event sharing for an application."
    },
    "moved_to_organization": {
      "type": "string",
      "description": "If the account was moved to a different organization, provides the name of that organization."
    },
    "admin_name": {
      "type": "string",
      "description": "Name of the account administrator."
    },
    "admin_password": {
      "type": "string",
      "description": "Password for the account administrator."
    },
    "admin_rsa_public_key": {
      "type": "string",
      "description": "RSA public key for the account administrator."
    },
    "admin_user_type": {
      "type": "string",
      "description": "User type of the account administrator."
    },
    "first_name": {
      "type": "string",
      "description": "First name of the account administrator."
    },
    "last_name": {
      "type": "string",
      "description": "Last name of the account administrator."
    },
    "email": {
      "type": "string",
      "description": "Email address of the account administrator."
    },
    "must_change_password": {
      "type": "boolean",
      "description": "Indicates whether the account administrator must change the password at the next login."
    },
    "polaris": {
      "type": "boolean",
      "description": "Indicates whether the account is a Polaris account."
    }
  }
}

=== api-evangelist/snowflake/examples/account-account-example.json
{
  "organization_name": "example_value",
  "region_group": "example_value",
  "region": "example_value",
  "edition": "example_value",
  "created_on": "example_value",
  "account_url": "https://www.example.com",
  "account_locator": "example_value",
  "account_locator_url": "https://www.example.com",
  "managed_accounts": 10,
  "consumption_billing_entity_name": "example_value",
  "marketplace_consumer_billing_entity_name": "example_value",
  "marketplace_provider_billing_entity_name": "example_value",
  "old_account_url": "https://www.example.com",
  "comment": "example_value",
  "is_org_admin": true,
  "retention_time": 10,
  "dropped_on": "example_value",
  "scheduled_deletion_time": "example_value",
  "restored_on": "example_value",
  "account_old_url_saved_on": "https://www.example.com",
  "account_old_url_last_used": "https://www.example.com",
  "organization_old_url": "https://www.example.com",
  "organization_old_url_saved_on": "https://www.example.com",
  "organization_old_url_last_used": "https://www.example.com",
  "organization_URL_expiration_on": "https://www.example.com",
  "moved_on": "example_value",
  "is_events_account": true,
  "moved_to_organization": "example_value",
  "admin_name": "example_value",
  "admin_password": "example_value",
  "admin_rsa_public_key": "example_value",
  "admin_user_type": "example_value",
  "first_name": "example_value",
  "last_name": "example_value",
  "email": "user@example.com",
  "must_change_password": true,
  "polaris": true
}
